In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn  as sns
df=pd.read_csv('11-iris.csv')
df = df.drop('Id',axis=1)
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()
df["Species"] = label.fit_transform(df["Species"])
X = df.drop("Species",axis=1)
y = df["Species"]
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=15)
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train_scaled,y_train)

GaussianNB()

In [3]:
y_pred = gnb.predict(X_test_scaled)
from sklearn.metrics import  confusion_matrix,accuracy_score,classification_report
print("Confussion matrix",confusion_matrix(y_test,y_pred))
print("Accuracy score",accuracy_score(y_test,y_pred))
print("Clasificitaion  report",classification_report(y_test,y_pred))

Confussion matrix [[12  0  0]
 [ 0 14  0]
 [ 0  0 12]]
Accuracy score 1.0
Clasificitaion  report               precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00        14
           2       1.00      1.00      1.00        12

    accuracy                           1.00        38
   macro avg       1.00      1.00      1.00        38
weighted avg       1.00      1.00      1.00        38



In [28]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()
logreg.fit(X_train,y_train)
y_pred = logreg.predict(X_test)
print("Confussion matrix",confusion_matrix(y_test,y_pred))
print("Accuracy score",accuracy_score(y_test,y_pred))
print("Clasificitaion  report",classification_report(y_test,y_pred))


Confussion matrix [[12  0  0]
 [ 0 14  0]
 [ 0  0 12]]
Accuracy score 1.0
Clasificitaion  report               precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00        14
           2       1.00      1.00      1.00        12

    accuracy                           1.00        38
   macro avg       1.00      1.00      1.00        38
weighted avg       1.00      1.00      1.00        38



In [29]:
penalty = ["l1","l2","elasticnet"]
c_values = [100,10,1,0.1,0.01]
solver = ["newton-cg","lbfgs","liblinear","sag","saga","newton-cholesky"]
class_weight = [{0:w,1:y} for w in [1,10,50,100] for y in [1,10,50,100]]
params = dict(penalty = penalty,C=c_values,solver=solver,class_weight = class_weight)
from sklearn.model_selection import GridSearchCV,StratifiedKFold
cv = StratifiedKFold()
grid = GridSearchCV(estimator=logreg,param_grid=params,scoring="accuracy",cv=cv)
grid.fit(X_train,y_train)


C:\Users\eymen\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:1296: FutureWarning: Using the 'liblinear' solver for multiclass classification is deprecated. An error will be raised in 1.8. Either use another solver which supports the multinomial loss or wrap the estimator in a OneVsRestClassifier to keep applying a one-versus-rest scheme.
  warnings.warn(
C:\Users\eymen\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:1296: FutureWarning: Using the 'liblinear' solver for multiclass classification is deprecated. An error will be raised in 1.8. Either use another solver which supports the multinomial loss or wrap the estimator in a OneVsRestClassifier to keep applying a one-versus-rest scheme.
  warnings.warn(
C:\Users\eymen\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:1296: FutureWarning: Using the 'liblinear' solver for multiclass classification is depr

Confussion matrix [[12  0  0]
 [ 0 14  0]
 [ 0  4  8]]
Accuracy score 0.8947368421052632
Clasificitaion  report               precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       0.78      1.00      0.88        14
           2       1.00      0.67      0.80        12

    accuracy                           0.89        38
   macro avg       0.93      0.89      0.89        38
weighted avg       0.92      0.89      0.89        38



C:\Users\eymen\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:1296: FutureWarning: Using the 'liblinear' solver for multiclass classification is deprecated. An error will be raised in 1.8. Either use another solver which supports the multinomial loss or wrap the estimator in a OneVsRestClassifier to keep applying a one-versus-rest scheme.
  warnings.warn(
C:\Users\eymen\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:1296: FutureWarning: Using the 'liblinear' solver for multiclass classification is deprecated. An error will be raised in 1.8. Either use another solver which supports the multinomial loss or wrap the estimator in a OneVsRestClassifier to keep applying a one-versus-rest scheme.
  warnings.warn(
C:\Users\eymen\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:1296: FutureWarning: Using the 'liblinear' solver for multiclass classification is depr

In [32]:
print(grid.best_params_)
print(grid.best_score_)

{'C': 100, 'class_weight': {0: 100, 1: 10}, 'penalty': 'l2', 'solver': 'sag'}
0.9735177865612649


In [14]:
from sklearn.svm import SVC
svc = SVC(kernel='linear')
svc.fit(X_train,y_train)
y_pred = svc.predict(X_test)
print("Confussion matrix",confusion_matrix(y_pred,y_test))
print("Accuracy score",accuracy_score(y_pred,y_test))
print("Clasificitaion  report",classification_report(y_pred,y_test))

Confussion matrix [[12  0  0]
 [ 0 13  0]
 [ 0  1 12]]
Accuracy score 0.9736842105263158
Clasificitaion  report               precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       0.93      1.00      0.96        13
           2       1.00      0.92      0.96        13

    accuracy                           0.97        38
   macro avg       0.98      0.97      0.97        38
weighted avg       0.98      0.97      0.97        38



In [16]:
from sklearn.svm import SVC
svc = SVC(kernel='rbf')
svc.fit(X_train,y_train)
y_pred = svc.predict(X_test)
print("Confussion matrix",confusion_matrix(y_pred,y_test))
print("Accuracy score",accuracy_score(y_pred,y_test))
print("Clasificitaion  report",classification_report(y_pred,y_test))

Confussion matrix [[12  0  0]
 [ 0 14  1]
 [ 0  0 11]]
Accuracy score 0.9736842105263158
Clasificitaion  report               precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      0.93      0.97        15
           2       0.92      1.00      0.96        11

    accuracy                           0.97        38
   macro avg       0.97      0.98      0.97        38
weighted avg       0.98      0.97      0.97        38



In [17]:
from sklearn.svm import SVC
svc = SVC(kernel='poly')
svc.fit(X_train,y_train)
y_pred = svc.predict(X_test)
print("Confussion matrix",confusion_matrix(y_pred,y_test))
print("Accuracy score",accuracy_score(y_pred,y_test))
print("Clasificitaion  report",classification_report(y_pred,y_test))

Confussion matrix [[12  0  0]
 [ 0 13  0]
 [ 0  1 12]]
Accuracy score 0.9736842105263158
Clasificitaion  report               precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       0.93      1.00      0.96        13
           2       1.00      0.92      0.96        13

    accuracy                           0.97        38
   macro avg       0.98      0.97      0.97        38
weighted avg       0.98      0.97      0.97        38



In [21]:
from sklearn.svm import SVC
svc = SVC(kernel='sigmoid')
svc.fit(X_train_scaled,y_train)
y_pred = svc.predict(X_test_scaled)
print("Confussion matrix",confusion_matrix(y_pred,y_test))
print("Accuracy score",accuracy_score(y_pred,y_test))
print("Clasificitaion  report",classification_report(y_pred,y_test))

Confussion matrix [[12  0  0]
 [ 0 12  1]
 [ 0  2 11]]
Accuracy score 0.9210526315789473
Clasificitaion  report               precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       0.86      0.92      0.89        13
           2       0.92      0.85      0.88        13

    accuracy                           0.92        38
   macro avg       0.92      0.92      0.92        38
weighted avg       0.92      0.92      0.92        38

